image: docker:latest

variables:
  # This should be set by docker image already, just to be sure...
  DOCKER_HOST: tcp://docker:2375
  # Use overlayfs driver for better performance
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

services:
  - name: docker:dind

before_script:
  - docker info

.docker-build-debian-package-devel:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - |
       docker build --build-arg IMAGE_ARCH=${IMAGE_ARCH} \
                    -f Dockerfile \
                    -t ${CI_REGISTRY_IMAGE}/${IMAGE_NAME} \
                    .
    - docker push ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}

docker-build-debian-package-devel-arm64v8:
  extends: .docker-build-debian-package-devel
  variables:
    IMAGE_ARCH: arm64v8
    IMAGE_NAME: arm64v8-debian-package-devel:bookworm

docker-build-debian-package-devel-arm32v7:
  extends: .docker-build-debian-package-devel
  variables:
    IMAGE_ARCH: arm32v7
    IMAGE_NAME: arm32v7-debian-package-devel:bookworm
