name: CI

on:
  push:

env:
  BUILD_WORLD: "1"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.12-dind
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.6

      - name: Build
        run: |
          cd builder && go get . && go run main.go
